### ISSUE TITLE
Travis not enabled

### ISSUE THREAD

**Issue by piotr-sokolowski** [stevebartholomew/newrelic_moped#34]
Hi
@stevebartholomew, could you check Travis-ci settings (https://travis-ci.org/stevebartholomew/newrelic_moped) ?
It looks like this repo is not enabled for testing in Travis.

Thanks.

**Comment by stevebartholomew** [comment]
@piotr-sokolowski just enabled and bumped - seems to be building now: https://travis-ci.org/stevebartholomew/newrelic_moped/builds/55146750

**Comment by piotr-sokolowski** [comment]
Thanks!
I know that we need to add test-unit as a gem because of Ruby 2.3 and Ruby 1.8.7 have to be removed. I'll do this and also I'll add other missing minor 2.x versions.

**Comment by stevebartholomew** [comment]
Great! Thanks for sorting this.
